#!/usr/bin/env bash
#
# scan-ai-traces.sh — busca rastros de agentes de IA (Claude, ChatGPT, OpenCode,
# Codex, etc.) en archivos de texto y en los metadatos de imágenes, diagramas,
# PDF y archivos .zip.
#
# Uso:  scan-ai-traces.sh [DIR|FILE] [opciones]
#       scan-ai-traces.sh --help
#
# Sale con 0 si no hay coincidencias, 1 si las hay y 2 ante un error de uso.

set -euo pipefail

DEFAULT_PATTERN="claude|anthropic|opencode|open[-_ ]?code|codex|chat[-_ ]?gpt|openai|\bgpt[0-9o.-]*|gemini|copilot|deepseek|aider|windsurf|codeium|tabnine|perplexity|\bqwen\b|moonshot|\bkimi\b|mistral|llama|groq|grok|sourcegraph cody|replit|devin|ollama|continue\.dev|ai[-_ ]generated|generated by (ai|claude|gpt|chatgpt|codex|opencode)|language model|large language model|\bllm\b|sonnet|\bopus\b|haiku|agent=[\"'][^\"']*"

IMG_EXTS=(png jpg jpeg gif tif tiff bmp webp heic heif avif ico)
SELF="$(realpath "$0")"
SELF_BASE="$(basename "$0")"

DIR="."
QUIET=0
JSON=0
DO_TEXT=1
DO_METADATA=1
DO_PDF=1
DO_ZIP=1
NO_DEFAULTS=0
PATTERNS_FILE=""
EXTRA=""
EXCLUDES=()
PREFIX=""
MAX_WIDTH=100
COLOR="auto"
USE_COLOR=0

usage() {
  cat <<EOF
scan-ai-traces.sh — busca rastros de agentes de IA en texto y metadatos

Uso:
  scan-ai-traces.sh [DIR|FILE] [opciones]

Argumentos:
  DIR|FILE                Carpeta o archivo a escanear (por defecto: .)

Opciones:
  -q, --quiet             Solo muestra el resumen final
      --no-text           No escanea archivos de texto
      --no-metadata       No escanea metadatos de imágenes/diagramas
      --no-pdf            No escanea PDF
      --no-zip            No descomprime ni escanea .zip
      --patterns <file>   Reemplaza los patrones por los del archivo (uno por línea)
      --extra <regex>     Agrega un patrón (ERE) a los existentes
      --no-defaults       No usa los patrones integrados
  -e, --exclude <glob>    Excluye archivos que coincidan (repetible)
      --max-width <n>     Ancho máximo del fragmento mostrado (por defecto: 100)
      --color <modo>      auto | always | never (por defecto: auto)
      --json              Salida en JSON
  -h, --help              Muestra esta ayuda

Ejemplos:
  scan-ai-traces.sh .
  scan-ai-traces.sh ./Figuras --no-pdf
  scan-ai-traces.sh . --extra 'mi-herramienta' --json
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    -q|--quiet) QUIET=1 ;;
    --no-text) DO_TEXT=0 ;;
    --no-metadata) DO_METADATA=0 ;;
    --no-pdf) DO_PDF=0 ;;
    --no-zip) DO_ZIP=0 ;;
    --patterns) PATTERNS_FILE="${2:-}"; shift ;;
    --extra) EXTRA="${2:-}"; shift ;;
    --no-defaults) NO_DEFAULTS=1 ;;
    -e|--exclude) EXCLUDES+=("${2:-}"); shift ;;
    --max-width) MAX_WIDTH="${2:-}"; shift ;;
    --color) COLOR="${2:-}"; shift ;;
    --json) JSON=1 ;;
    -h|--help) usage; exit 0 ;;
    --) shift; [ $# -gt 0 ] && DIR="$1"; break ;;
    -*) echo "Opción desconocida: $1" >&2; usage >&2; exit 2 ;;
    *) DIR="$1" ;;
  esac
  shift
done

PATTERN=""
if [ "$NO_DEFAULTS" != 1 ]; then PATTERN="$DEFAULT_PATTERN"; fi
if [ -n "$PATTERNS_FILE" ]; then
  [ -f "$PATTERNS_FILE" ] || { echo "No existe el archivo de patrones: $PATTERNS_FILE" >&2; exit 2; }
  PATTERN="$(grep -vE '^[[:space:]]*(#|$)' "$PATTERNS_FILE" | paste -sd '|' -)"
fi
if [ -n "$EXTRA" ]; then
  PATTERN="${PATTERN:+$PATTERN|}${EXTRA}"
fi
[ -n "$PATTERN" ] || { echo "No hay patrones que buscar." >&2; exit 2; }

[[ "$MAX_WIDTH" =~ ^[0-9]+$ ]] && [ "$MAX_WIDTH" -gt 0 ] || { echo "Ancho inválido: $MAX_WIDTH" >&2; exit 2; }
case "$COLOR" in
  auto) [ -t 1 ] && USE_COLOR=1 ;;
  always) USE_COLOR=1 ;;
  never) USE_COLOR=0 ;;
  *) echo "Modo de color inválido: $COLOR (usa auto|always|never)" >&2; exit 2 ;;
esac
if [ "$USE_COLOR" = 1 ]; then
  C_FILE=$'\033[1;36m'; C_LABEL=$'\033[33m'; C_HIT=$'\033[1;31m'; C_RST=$'\033[0m'
else
  C_FILE=""; C_LABEL=""; C_HIT=""; C_RST=""
fi

RESULTS="$(mktemp)"
TMPDIRS=()
cleanup() {
  rm -f "$RESULTS"
  local d
  for d in "${TMPDIRS[@]}"; do if [ -n "$d" ]; then rm -rf "$d"; fi; done
}
trap cleanup EXIT

append() {
  printf '%s\x1f%s\x1f%s\x1f%s\n' "${PREFIX}${1#./}" "$2" "$3" "$4" >>"$RESULTS"
}

# Decodifica %XX de una cadena URL-encoded (para los metadatos de PNG, que
# guardan el XML del diagrama codificado). Sin dependencias externas.
maybe_urldecode() {
  local s="$1"
  [[ "$s" == *%[0-9A-Fa-f][0-9A-Fa-f]* ]] || { printf '%s' "$s"; return; }
  printf '%b' "${s//%/\\x}"
}

# Devuelve una ventana de `width` caracteres centrada en la primera coincidencia
# del patrón, con el término resaltado y elipsis si se recorta.
snippet() {
  local text="$1" width="${2:-$MAX_WIDTH}"
  local match prefix off mlen half start end seg
  text="${text//$'\n'/ }"; text="${text//$'\r'/ }"; text="${text//$'\t'/ }"
  match=$(printf '%s' "$text" | grep -oE -e "$PATTERN" 2>/dev/null | head -1)
  if [ -n "$match" ]; then
    prefix="${text%%"$match"*}"
    off=${#prefix}
    mlen=${#match}
  else
    off=0; mlen=0
  fi

  if [ "${#text}" -le "$width" ]; then
    seg="$text"; start=0; end=${#text}
  else
    half=$(( width / 2 ))
    start=$(( off - half )); [ "$start" -lt 0 ] && start=0
    end=$(( start + width )); [ "$end" -gt "${#text}" ] && end=${#text}
    start=$(( end - width )); [ "$start" -lt 0 ] && start=0
    seg="${text:start:$((end-start))}"
  fi

  if [ "$USE_COLOR" = 1 ] && [ -n "$match" ]; then
    local moff=$(( off - start ))
    if [ "$moff" -ge 0 ] && [ "$(( moff + mlen ))" -le "${#seg}" ]; then
      seg="${seg:0:moff}${C_HIT}${seg:moff:mlen}${C_RST}${seg:$((moff+mlen))}"
    fi
  fi

  local pre="" post=""
  [ "$start" -gt 0 ] && pre="…"
  [ "$end" -lt "${#text}" ] && post="…"
  printf '%s%s%s' "$pre" "$seg" "$post"
}

# --- patrones para grep/find ------------------------------------------------
GREP_EXCLUDES=()
FIND_EXCLUDES=()
for g in "${EXCLUDES[@]}"; do
  [ -n "$g" ] || continue
  GREP_EXCLUDES+=(--exclude="$g")
  FIND_EXCLUDES+=(! -name "$g")
done

# --- escaneo por archivo ----------------------------------------------------
scan_text_file() {
  local f="$1" line
  while IFS= read -r line; do
    [ -n "$line" ] && append "$f" "texto" "${line%%:*}" "${line#*:}"
  done < <(grep -niIE -e "$PATTERN" -- "$f" 2>/dev/null || true)
}

scan_metadata_file() {
  local f="$1" m grp tag val rest
  while IFS= read -r m; do
    [ -n "$m" ] || continue
    grp="${m#[}"; grp="${grp%%]*}"
    rest="${m#*]}"; rest="${rest#"${rest%%[![:space:]]*}"}"
    tag="${rest%%:*}"; tag="${tag%"${tag##*[![:space:]]}"}"
    val="${rest#*:}"; val="${val#"${val%%[![:space:]]*}"}"
    append "$f" "metadatos" "$grp:$tag" "$val"
  done < <(exiftool -s -a -G1 --System:all --File:all -- "$f" 2>/dev/null | grep -iE -e "$PATTERN" || true)
  while IFS= read -r m; do
    [ -n "$m" ] && append "$f" "binario" "" "$m"
  done < <(strings -a -n 5 "$f" 2>/dev/null | grep -iE -e "$PATTERN" || true)
}

scan_pdf_file() {
  local f="$1" m grp tag val rest
  while IFS= read -r m; do
    [ -n "$m" ] || continue
    grp="${m#[}"; grp="${grp%%]*}"
    rest="${m#*]}"; rest="${rest#"${rest%%[![:space:]]*}"}"
    tag="${rest%%:*}"; tag="${tag%"${tag##*[![:space:]]}"}"
    val="${rest#*:}"; val="${val#"${val%%[![:space:]]*}"}"
    append "$f" "pdf-metadatos" "$grp:$tag" "$val"
  done < <(exiftool -s -a -G1 --System:all --File:all -- "$f" 2>/dev/null | grep -iE -e "$PATTERN" || true)
  while IFS= read -r m; do
    [ -n "$m" ] && append "$f" "pdf-texto" "${m%%:*}" "${m#*:}"
  done < <(pdftotext "$f" - 2>/dev/null | grep -inE -e "$PATTERN" || true)
}

scan_zip_file() {
  local z="$1" tmp
  tmp="$(mktemp -d)"
  TMPDIRS+=("$tmp")
  if unzip -qq -o "$z" -d "$tmp" >/dev/null 2>&1; then
    ( cd "$tmp" && PREFIX="$z!" && scan_dir "." )
  fi
}

# --- escaneo por directorio -------------------------------------------------
is_image() {
  local f="${1,,}"
  local e
  for e in "${IMG_EXTS[@]}"; do
    [[ "$f" == *".$e" ]] && return 0
  done
  return 1
}

scan_dir() {
  local dir="$1" f line

  if [ "$DO_TEXT" = 1 ]; then
    while IFS= read -r line; do
      if [ -n "$line" ]; then
        local rest="${line#*:}"
        append "${line%%:*}" "texto" "${rest%%:*}" "${rest#*:}"
      fi
    done < <(grep -rInEi -I --exclude-dir=node_modules --exclude-dir=.git \
                "${GREP_EXCLUDES[@]}" --exclude="$SELF_BASE" \
                -e "$PATTERN" "$dir" 2>/dev/null || true)
  fi

  if [ "$DO_METADATA" = 1 ] || [ "$DO_PDF" = 1 ]; then
    while IFS= read -r f; do
      if [ "$DO_PDF" = 1 ] && [[ "${f,,}" == *.pdf ]]; then
        scan_pdf_file "$f"
      elif [ "$DO_METADATA" = 1 ] && is_image "$f"; then
        scan_metadata_file "$f"
      fi
    done < <(find "$dir" -type f -not -path '*/node_modules/*' -not -path '*/.git/*' \
                  "${FIND_EXCLUDES[@]}" 2>/dev/null)
  fi

  if [ "$DO_ZIP" = 1 ]; then
    while IFS= read -r f; do
      scan_zip_file "$f"
    done < <(find "$dir" -type f -iname '*.zip' -not -path '*/node_modules/*' \
                  -not -path '*/.git/*' "${FIND_EXCLUDES[@]}" 2>/dev/null)
  fi
}

scan_path() {
  local p="$1"
  if [ -f "$p" ]; then
    if [ "$DO_PDF" = 1 ] && [[ "${p,,}" == *.pdf ]]; then
      scan_pdf_file "$p"
    elif [ "$DO_ZIP" = 1 ] && [[ "${p,,}" == *.zip ]]; then
      scan_zip_file "$p"
    elif [ "$DO_METADATA" = 1 ] && is_image "$p"; then
      scan_metadata_file "$p"
    elif [ "$DO_TEXT" = 1 ]; then
      scan_text_file "$p"
    fi
  elif [ -d "$p" ]; then
    scan_dir "$p"
  else
    echo "No existe: $p" >&2
    exit 2
  fi
}

scan_path "$DIR"

# --- reporte ----------------------------------------------------------------
count=$(wc -l <"$RESULTS" | tr -d '[:space:]')
files=$(cut -d$'\x1f' -f1 "$RESULTS" 2>/dev/null | sort -u | wc -l | tr -d '[:space:]')

if [ "$JSON" = 1 ]; then
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$RESULTS" <<'PY'
import json, sys
rows = []
with open(sys.argv[1], encoding='utf-8', errors='replace') as fh:
    for line in fh:
        line = line.rstrip('\n')
        if not line:
            continue
        parts = line.split('\x1f')
        while len(parts) < 4:
            parts.append('')
        rows.append({'file': parts[0], 'source': parts[1], 'detail': parts[2], 'match': parts[3]})
print(json.dumps(rows, ensure_ascii=False, indent=2))
PY
  else
    echo "[]"
  fi
else
  if [ "$QUIET" != 1 ] && [ "$count" -gt 0 ]; then
    while IFS=$'\x1f' read -r f s d m; do
      case "$s" in
        binario|metadatos|pdf-metadatos) m="$(maybe_urldecode "$m")" ;;
      esac
      case "$s" in
        texto|pdf-texto) disp="${f}:${d}"; label="$s" ;;
        *)               disp="$f";      label="$s${d:+:$d}" ;;
      esac
      printf '%s%s%s [%s%s%s] %s\n' \
        "$C_FILE" "$disp" "$C_RST" "$C_LABEL" "$label" "$C_RST" "$(snippet "$m")"
    done < <(sort -s -t$'\x1f' -k1,1 "$RESULTS")
    echo
  fi
  if [ "$count" -gt 0 ]; then
    echo "Rastros de IA: $count coincidencia(s) en $files archivo(s)."
  else
    echo "Rastros de IA: sin coincidencias."
  fi
fi

[ "$count" -gt 0 ] && exit 1
exit 0
